### ISSUE TITLE
Sleeping will result in the day counter being set back to 0 (or 1 in some cases, seemingly random)

### ISSUE THREAD

**Issue by UwUPeanut** [KwemberDev/SimpleNightmares#4]
Title, normally wouldnt be a huge issue, but a lot of modpacks rely on timestages and the day counter for progression, and sleeping resets all of this (version 1.1.10)

**Comment by KwemberDev** [comment]
Hi! Thank you for noticing, the issue has been fixed in the newly uploaded version.
